"""add_department_to_users

Revision ID: 522cec1eedc7
Revises: 620970298619
Create Date: 2026-08-11 20:04:52.136005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522cec1eedc7'
down_revision = '620970298619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_search_vector'), table_name='document_chunks', postgresql_using='gin')
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.create_index(op.f('ix_document_chunks_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
