"""add security groups and rda queries trace

Revision ID: 620970298619
Revises: ded5fcdfe41d
Create Date: 2026-08-11 17:14:14.478959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620970298619'
down_revision = 'ded5fcdfe41d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_groups_name'), 'security_groups', ['name'], unique=True)
    op.create_table('user_security_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['security_group_id'], ['security_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'security_group_id')
    )
    op.create_table('document_security_groups',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('security_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_group_id'], ['security_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'security_group_id')
    )
    op.add_column('rda_queries', sa.Column('confidence', sa.String(length=50), nullable=True))
    op.add_column('rda_queries', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('rda_queries', sa.Column('citation_count', sa.Integer(), nullable=True))
    op.add_column('rda_queries', sa.Column('abstained', sa.Boolean(), nullable=True))
    
    # Seed default groups
    op.execute("INSERT INTO security_groups (name, description) VALUES ('default', 'Default Security Group') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO security_groups (name, description) VALUES ('operations', 'Operations Group') ON CONFLICT DO NOTHING")
    op.execute("INSERT INTO security_groups (name, description) VALUES ('safety', 'Safety Group') ON CONFLICT DO NOTHING")
    
    # Assign existing users to default
    op.execute("""
    INSERT INTO user_security_groups (user_id, security_group_id)
    SELECT u.id, sg.id FROM users u, security_groups sg
    WHERE sg.name = 'default'
    ON CONFLICT DO NOTHING
    """)

    # Assign existing documents to default
    op.execute("""
    INSERT INTO document_security_groups (document_id, security_group_id)
    SELECT d.id, sg.id FROM documents d, security_groups sg
    WHERE sg.name = 'default'
    ON CONFLICT DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rda_queries', 'abstained')
    op.drop_column('rda_queries', 'citation_count')
    op.drop_column('rda_queries', 'model_name')
    op.drop_column('rda_queries', 'confidence')
    op.drop_table('document_security_groups')
    op.drop_table('user_security_groups')
    op.drop_index(op.f('ix_security_groups_name'), table_name='security_groups')
    op.drop_table('security_groups')
    # ### end Alembic commands ###
