"""add citations to conversation messages

Revision ID: 6a72c013cc75
Revises: df91a6f55099
Create Date: 2026-08-13 16:39:31.548339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a72c013cc75'
down_revision = 'df91a6f55099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('citations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'citations')
    # ### end Alembic commands ###
