"""add section, security_group, content_hash to document_chunks

Revision ID: ded5fcdfe41d
Revises: 67127c2bff01
Create Date: 2026-08-09 10:59:58.777266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded5fcdfe41d'
down_revision = '67127c2bff01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rda_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rda_queries_request_id'), 'rda_queries', ['request_id'], unique=True)
    op.add_column('document_chunks', sa.Column('section', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('security_group', sa.String(length=100), nullable=True))
    op.add_column('document_chunks', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_column('document_chunks', 'content_hash')
    op.drop_column('document_chunks', 'security_group')
    op.drop_column('document_chunks', 'section')
    op.drop_index(op.f('ix_rda_queries_request_id'), table_name='rda_queries')
    op.drop_table('rda_queries')
    # ### end Alembic commands ###
